package visao;

import controle.ConectaBanco;
import controle.ControleProdutos;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

import util.Sorteio;
import modelo.ModeloProduto;
import modelo.ModeloTabela;
import modelo.NimbusClasse;
import novo.SelecionarCodigosBarrasDao;

import java.text.NumberFormat;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.AbstractAction;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import util.TarefasSegundoPlano;

public class FrmCadastraProduto extends javax.swing.JFrame {

    ConectaBanco conecta = new ConectaBanco();
    ConectaBanco conectapesquisa = new ConectaBanco();
    ConectaBanco conectacategoria = new ConectaBanco();
    ModeloProduto mod = new ModeloProduto();
    ModeloProduto model = new ModeloProduto();
    ControleProdutos control = new ControleProdutos();
    DecimalFormat df = new DecimalFormat("0.00");
    NimbusClasse n = new NimbusClasse();
    NumberFormat calculo;
    int idProd;
    float pv, p, precoCompra, lucroEsperado, precoVenda;

    public FrmCadastraProduto() {
        initComponents();
        //linha implementada codigo de barras
        codigobarras();
        //
        setIcon();
        preencherCombo();
        jLabelCarregando.setVisible(false);
        //this.setExtendedState(MAXIMIZED_BOTH);
        //desabilitarCampos();
        jComboBoxCategorias.removeAllItems();
        preencherComboCategorias();

        IniciaId();

        novoProduto();
        EditaProduto();
        salvaProduto();
        ExcluirProduto();
        Sair();
        calculo = NumberFormat.getInstance();
        calculo.setMinimumFractionDigits(2);
        jTextFieldLucroEsperado.setText("0,00");
        jTextFieldLucro.setText("0,00");
        jTextFieldPrecoCompra.setText("0,00");
        jTextFieldPrecoVenda.setText("0,00");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPrecoCompra = new javax.swing.JTextField();
        jTextFieldPrecoVenda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldLucroEsperado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxFornecedor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldQuantidadeMinima = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxUnidade = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldLucro = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldBarras = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxCategorias = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButtonVisualizar = new javax.swing.JButton();
        jLabelCarregando = new javax.swing.JLabel();

        jLabel8.setText("Lucro Esperado %");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 181, 181));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 32767));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 681));

        jButtonNovo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNovo.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonNovo.setForeground(new java.awt.Color(0, 153, 153));
        jButtonNovo.setText("Novo (F6)");
        jButtonNovo.setToolTipText("Novo");
        jButtonNovo.setBorder(null);
        jButtonNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(0, 153, 153));
        jButtonSalvar.setText("Salvar (F12)");
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.setBorder(null);
        jButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(0, 153, 153));
        jButtonEditar.setText("Editar (F8)");
        jButtonEditar.setToolTipText("Editar");
        jButtonEditar.setBorder(null);
        jButtonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(0, 153, 153));
        jButtonExcluir.setText("Excluir (Del)");
        jButtonExcluir.setToolTipText("Excluir");
        jButtonExcluir.setBorderPainted(false);
        jButtonExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPesquisar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonPesquisar.setForeground(new java.awt.Color(0, 153, 153));
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonPesquisar.setBorderPainted(false);
        jButtonPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonSair.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSair.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(0, 153, 153));
        jButtonSair.setText("Sair (ESC)");
        jButtonSair.setToolTipText("Sair");
        jButtonSair.setBorderPainted(false);
        jButtonSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jTextFieldPesquisar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextFieldPesquisar.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldPesquisar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyReleased(evt);
            }
        });

        tabela.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        tabela.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabela.setForeground(new java.awt.Color(51, 51, 51));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.setGridColor(new java.awt.Color(255, 255, 255));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Preço de compra: ");

        jTextFieldPrecoCompra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPrecoCompra.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldPrecoCompra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldPrecoCompra.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldPrecoCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPrecoCompraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPrecoCompraFocusLost(evt);
            }
        });
        jTextFieldPrecoCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPrecoCompraMouseClicked(evt);
            }
        });

        jTextFieldPrecoVenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPrecoVenda.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldPrecoVenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldPrecoVenda.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldPrecoVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPrecoVendaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPrecoVendaFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Preço de venda: ");

        jTextFieldLucroEsperado.setEditable(false);
        jTextFieldLucroEsperado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldLucroEsperado.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldLucroEsperado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldLucroEsperado.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldLucroEsperado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLucroEsperadoFocusLost(evt);
            }
        });
        jTextFieldLucroEsperado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLucroEsperadoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Margem bruta %");

        jComboBoxFornecedor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxFornecedor.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxFornecedor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fornecedor:");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("+");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldQuantidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldQuantidade.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldQuantidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldQuantidade.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Estoque:");

        jTextFieldQuantidadeMinima.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldQuantidadeMinima.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldQuantidadeMinima.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldQuantidadeMinima.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Estoque minimo");

        jComboBoxUnidade.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jComboBoxUnidade.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidade\t", "Par", "Litro", "Caixa 12x1", " " }));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Medida:");

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Lucro de venda: ");

        jTextFieldLucro.setEditable(false);
        jTextFieldLucro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldLucro.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldLucro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldLucro.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldLucro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLucroFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldLucroEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBoxFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldQuantidadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jTextFieldPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(43, 43, 43)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(43, 43, 43)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldLucroEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel5))
                                    .addGap(43, 43, 43))))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxUnidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldQuantidadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));

        jTextFieldCodigo.setEditable(false);
        jTextFieldCodigo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCodigo.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldCodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldCodigo.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldCodigo.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Código:");

        jTextFieldBarras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldBarras.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldBarras.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldBarras.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Código de barras:");

        jTextFieldProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldProduto.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jTextFieldProduto.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome do produto:");

        jComboBoxCategorias.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxCategorias.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxCategorias.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Categoria:");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setText("+");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBoxCategorias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jButtonVisualizar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVisualizar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonVisualizar.setForeground(new java.awt.Color(0, 153, 153));
        jButtonVisualizar.setText("Visualizar Produtos");
        jButtonVisualizar.setBorderPainted(false);
        jButtonVisualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarActionPerformed(evt);
            }
        });

        jLabelCarregando.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCarregando.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCarregando.setText("CARREGANDO RELATÓRIO...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelCarregando)
                        .addGap(109, 109, 109)
                        .addComponent(jButtonVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCarregando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1361, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void codigobarras() {
        jTextFieldBarras.setText(new Sorteio().sortearNumero(18, new SelecionarCodigosBarrasDao().selectCredits()));
    }
    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        Cadastrar();
        limpaCampos();
        IniciaId();
        jTextFieldBarras.requestFocus();
        codigobarras();

    }//GEN-LAST:event_jButtonSalvarActionPerformed
    public void Cadastrar() {

        conecta.conexao();
        String name = jTextFieldProduto.getText();
        conecta.executaSQL("select nome_produto from produto where nome_produto='" + name + "'");
        try {

            if (conecta.rs.next()) {

                JOptionPane.showMessageDialog(null, "O Produto " + name + " já foi Cadastrado");

            } else {

                mod.setFornecedorProduto((String) jComboBoxFornecedor.getSelectedItem());
                mod.setCodigobarras(jTextFieldBarras.getText());
                mod.setNomeProduto(jTextFieldProduto.getText());
                mod.setPrecoCompra(Float.parseFloat(jTextFieldPrecoCompra.getText().replace(",", ".")));
                mod.setLucroVenda(Float.parseFloat(jTextFieldLucro.getText().replace(",", ".")));
                mod.setLucroesperado(Float.parseFloat(jTextFieldLucroEsperado.getText().replace(",", ".")));
                mod.setPrecoVenda(Float.parseFloat(jTextFieldPrecoVenda.getText().replace(",", ".")));
                mod.setQtdProduto(Integer.parseInt(jTextFieldQuantidade.getText()));
                mod.setQuantidadeM(Integer.parseInt(jTextFieldQuantidadeMinima.getText()));
                mod.setCategoria((String) jComboBoxCategorias.getSelectedItem());
                mod.setUnidade((String) jComboBoxUnidade.getSelectedItem());

                control.InserirProduto(mod);

                limpaCampos();
                preencherTabela("SELECT * FROM produto INNER JOIN fornecedor ON produto.id_fornecedor = fornecedor.id_fornecedor INNER JOIN categorias ON produto.id_categoria = categorias.id_categoria ORDER BY nome_produto ASC");
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmCadastraProduto.class.getName()).log(Level.SEVERE, null, ex);
        } finally {

            conecta.desconecta();

        }

    }
    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        mod.setIdProduto(Integer.parseInt(jTextFieldCodigo.getText()));
        mod.setCodigobarras(jTextFieldBarras.getText());
        mod.setFornecedorProduto((String) jComboBoxFornecedor.getSelectedItem());
        mod.setUnidade((String) jComboBoxUnidade.getSelectedItem());
        mod.setNomeProduto(jTextFieldProduto.getText());
        mod.setPrecoCompra(Float.parseFloat(jTextFieldPrecoCompra.getText().replace(",", ".")));
        mod.setLucroVenda(Float.parseFloat(jTextFieldLucro.getText().replace(",", ".")));
        mod.setLucroesperado(Float.parseFloat(jTextFieldLucroEsperado.getText().replace(",", ".")));
        mod.setPrecoVenda(Float.parseFloat(jTextFieldPrecoVenda.getText().replace(",", ".")));
        mod.setQtdProduto(Integer.parseInt(jTextFieldQuantidade.getText()));
        mod.setQuantidadeM(Integer.parseInt(jTextFieldQuantidadeMinima.getText()));

        control.AlterarProduto(mod);
        preencherTabela("SELECT * FROM produto INNER JOIN fornecedor ON produto.id_fornecedor = fornecedor.id_fornecedor INNER JOIN categorias ON produto.id_categoria = categorias.id_categoria ORDER BY nome_produto ASC");
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        String message = "Deseja Excluir Produto ?";
        String title = "Excluir Produto";

        int result = JOptionPane.showConfirmDialog(this, message, title, JOptionPane.YES_OPTION);

        if (result == JOptionPane.YES_OPTION) {

            mod.setIdProduto(Integer.parseInt(jTextFieldCodigo.getText()));
            control.ExcluirProduto(mod);
            preencherTabela("SELECT * FROM produto INNER JOIN fornecedor ON produto.id_fornecedor = fornecedor.id_fornecedor INNER JOIN categorias ON produto.id_categoria = categorias.id_categoria ORDER BY nome_produto ASC");
            limpaCampos();
        } else {

            JOptionPane.showMessageDialog(null, "Produto não Excluido");
        }


    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jTextFieldProduto.setEnabled(true);
        jTextFieldPrecoCompra.setEnabled(true);
        jTextFieldLucroEsperado.setEnabled(true);
        jTextFieldPrecoVenda.setEnabled(true);
        jTextFieldBarras.setEnabled(true);
        jTextFieldQuantidade.setEnabled(true);
        jTextFieldQuantidadeMinima.setEnabled(true);
        mod.setPesquisa(jTextFieldPesquisar.getText());
        ModeloProduto model = control.buscaProduto(mod);

//        jTextFieldCodigo.setText(String.valueOf(model.getIdProduto()));
//        jTextFieldProduto.setText(model.getNomeProduto());
//        jTextFieldPrecoCompra.setText(String.valueOf(model.getPrecoCompra()));
//        jTextFieldLucroEsperado.setText(String.valueOf(model.getPrecoVenda()));
//        jTextFieldQuantidade.setText(String.valueOf(model.getQtdProduto()));
//        jComboBoxFornecedor.setSelectedItem(model.getFornecedorProduto());
        if (jTextFieldPesquisar.getText().equals("")) {
            preencherTabela("SELECT * FROM produto INNER JOIN fornecedor ON produto.id_fornecedor = fornecedor.id_fornecedor INNER JOIN categorias ON produto.id_categoria = categorias.id_categoria ORDER BY nome_produto ASC");
        } else {
            preencherTabela("SELECT * FROM produto INNER JOIN fornecedor ON produto.id_fornecedor = fornecedor.id_fornecedor ON produto.id_categoria = categorias.id_categoria  WHERE nome_produto LIKE '%" + jTextFieldPesquisar.getText() + "%'");
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        jButtonSalvar.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonNovo.setEnabled(true);
        String nome_produto = "" + tabela.getValueAt(tabela.getSelectedRow(), 1);
        String pCompra = "" + tabela.getValueAt(tabela.getSelectedRow(), 2);
        String pVenda = "" + tabela.getValueAt(tabela.getSelectedRow(), 3);
        String lVenda = "" + tabela.getValueAt(tabela.getSelectedRow(), 4);
        String pLucro = "" + tabela.getValueAt(tabela.getSelectedRow(), 5);

        jTextFieldPrecoCompra.setText(String.valueOf(pCompra).replace(".", ","));
        jTextFieldLucro.setText(String.valueOf(lVenda).replace(".", ","));
        jTextFieldLucroEsperado.setText(String.valueOf(pLucro).replace(".", ","));
        jTextFieldPrecoVenda.setText(String.valueOf(pVenda).replace(".", ","));
        conecta.conexao();
        conectapesquisa.conexao();
        conectacategoria.conexao();
        conecta.executaSQL("SELECT * FROM produto WHERE nome_produto ='" + nome_produto + "'");
        try {
            conecta.rs.first();
            jTextFieldCodigo.setText(String.valueOf(conecta.rs.getInt("id_produto")));
            jTextFieldBarras.setText(conecta.rs.getString("codigobarras"));
            jTextFieldProduto.setText(conecta.rs.getString("nome_produto"));
            jComboBoxUnidade.setSelectedItem(conecta.rs.getString("unidade"));
            //jTextFieldPrecoCompra.setText(String.valueOf(conecta.rs.getFloat("preco_compra")));
            //jTextFieldLucroEsperado.setText(String.valueOf(conecta.rs.getInt("lucro_esperado")));
            //jTextFieldPrecoVenda.setText(String.valueOf(conecta.rs.getFloat("preco_venda")));
            jTextFieldQuantidade.setText(String.valueOf(conecta.rs.getInt("quantidade")));
            jTextFieldQuantidadeMinima.setText(String.valueOf(conecta.rs.getInt("quantidade_minima")));

            conectapesquisa.executaSQL("SELECT * FROM fornecedor WHERE id_fornecedor =" + conecta.rs.getInt("id_fornecedor"));
            conectapesquisa.rs.first();
            jComboBoxFornecedor.setSelectedItem(conectapesquisa.rs.getString("nome_fornecedor"));

            conectacategoria.executaSQL("SELECT * FROM categorias WHERE id_categoria =" + conecta.rs.getInt("id_categoria"));
            conectacategoria.rs.first();
            jComboBoxCategorias.setSelectedItem(conectacategoria.rs.getString("nome_categoria"));

            conectacategoria.desconecta();
            conectapesquisa.desconecta();
            conecta.desconecta();
            //JOptionPane.showMessageDialog(null, nome_produto);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Selecionar os Dados" + ex);
        } finally {

            conecta.desconecta();

        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmFornecedores frm = new FrmFornecedores();
        frm.setVisible(true);
        preencherCombo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed

        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jTextFieldPrecoCompra.setEnabled(true);
        jTextFieldLucroEsperado.setEnabled(true);
        jTextFieldProduto.setEnabled(true);
        jTextFieldQuantidadeMinima.setEnabled(true);
        //jTextFieldBarras.setEnabled(true);
        jTextFieldPrecoVenda.setEnabled(true);
        jTextFieldQuantidade.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldBarras.requestFocus();
        limpaCampos();
        IniciaId();
        codigobarras();

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jTextFieldPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (!jTextFieldPesquisar.getText().equals("")) {

                jButtonEditar.setEnabled(true);
                jButtonExcluir.setEnabled(true);
                jTextFieldProduto.setEnabled(true);
                jTextFieldPrecoCompra.setEnabled(true);
                jTextFieldLucroEsperado.setEnabled(true);
                jTextFieldQuantidade.setEnabled(true);
                jTextFieldPrecoVenda.setEnabled(true);
                jTextFieldBarras.setEnabled(true);
                jTextFieldQuantidadeMinima.setEnabled(true);
                mod.setPesquisa(jTextFieldPesquisar.getText());
                ModeloProduto model = control.buscaProduto(mod);

                jTextFieldBarras.setText(String.valueOf(model.getCodigobarras()));
                jTextFieldCodigo.setText(String.valueOf(model.getIdProduto()));
                jTextFieldProduto.setText(model.getNomeProduto());
                jTextFieldPrecoCompra.setText(String.valueOf(df.format(model.getPrecoCompra())).replace(".", ","));
                jTextFieldLucroEsperado.setText(String.valueOf(df.format(model.getLucroesperado())).replace(".", ","));
                jTextFieldPrecoVenda.setText(String.valueOf(df.format(model.getPrecoVenda())).replace(".", ","));
                jTextFieldQuantidade.setText(String.valueOf(model.getQtdProduto()));
                jTextFieldQuantidadeMinima.setText(String.valueOf(model.getQuantidadeM()));
                jComboBoxFornecedor.setSelectedItem(model.getFornecedorProduto());
                jComboBoxCategorias.setSelectedItem(model.getCategoria());

                preencherTabela("SELECT * FROM produto INNER JOIN fornecedor ON produto.id_fornecedor = fornecedor.id_fornecedor WHERE nome_produto LIKE '%" + jTextFieldPesquisar.getText() + "%'");

            } else {

                JOptionPane.showMessageDialog(rootPane, "Digite o nome do Produto ou Parte do Nome");

            }

        }
    }//GEN-LAST:event_jTextFieldPesquisarKeyPressed

    private void jTextFieldLucroEsperadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLucroEsperadoFocusLost
//        String recebePCompra = jTextFieldPrecoCompra.getText().replace(",",".");
//        
//        float precoCompra = Float.parseFloat(recebePCompra);
//        
//        float lucroEsperado = Float.parseFloat(jTextFieldLucroEsperado.getText().replace(",", "."));
//        
//        pv = (precoCompra * lucroEsperado) / 100 + precoCompra;
//         
//        
//         jTextFieldPrecoCompra.setText(String.valueOf(df.format(precoCompra)));       
        //jTextFieldPrecoVenda.setText(String.valueOf(df.format(pv)));

    }//GEN-LAST:event_jTextFieldLucroEsperadoFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FrmCategorias cat = new FrmCategorias();
        cat.setVisible(true);
        jComboBoxCategorias.removeAllItems();
        preencherComboCategorias();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldPrecoCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPrecoCompraFocusLost
        String pegaValor = jTextFieldPrecoCompra.getText();
        String novoValor = pegaValor.replace(" ", "").replace(".", "").replace(",", ".");
        precoCompra = Float.parseFloat(novoValor);
        DecimalFormat df = new DecimalFormat("0.00");
        String valorFormatado = df.format(precoCompra);
        jTextFieldPrecoCompra.setText(valorFormatado);


    }//GEN-LAST:event_jTextFieldPrecoCompraFocusLost

    private void jTextFieldPrecoCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPrecoCompraMouseClicked

        jTextFieldPrecoCompra.selectAll();
    }//GEN-LAST:event_jTextFieldPrecoCompraMouseClicked

    private void jTextFieldPrecoVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPrecoVendaFocusLost
//        String recebePCompra = jTextFieldPrecoCompra.getText();
//        String novoRecebep = recebePCompra.replace(" ", "").replace("R$", "").replace(",", ".");

        float precoCompra = Float.parseFloat(jTextFieldPrecoCompra.getText().replace(",", "."));

        float precoVenda = Float.parseFloat(jTextFieldPrecoVenda.getText().replace(",", "."));
        float lucro = precoVenda - precoCompra;
        float p = (lucro / precoVenda) * 100;

        String pcf = df.format(p);
        jTextFieldPrecoCompra.setText(String.valueOf(df.format(precoCompra)));
        jTextFieldPrecoVenda.setText(String.valueOf(df.format(precoVenda)));
        jTextFieldLucroEsperado.setText(String.valueOf(pcf));
        jTextFieldLucro.setText(String.valueOf(df.format(lucro)));


    }//GEN-LAST:event_jTextFieldPrecoVendaFocusLost

    private void jTextFieldLucroEsperadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLucroEsperadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLucroEsperadoActionPerformed

    private void jButtonVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarActionPerformed

        new Thread() {
            public void run() {
                jLabelCarregando.setVisible(true);
                TarefasSegundoPlano v = new TarefasSegundoPlano();
                v.relatorioProdutos();
                jLabelCarregando.setVisible(false);
            }

        }.start();


    }//GEN-LAST:event_jButtonVisualizarActionPerformed

    private void jTextFieldPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyReleased
        preencherTabela("SELECT * FROM produto INNER JOIN fornecedor ON produto.id_fornecedor = fornecedor.id_fornecedor WHERE nome_produto LIKE '%" + jTextFieldPesquisar.getText() + "%'");

    }//GEN-LAST:event_jTextFieldPesquisarKeyReleased

    private void jTextFieldLucroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLucroFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLucroFocusLost

    private void jTextFieldPrecoCompraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPrecoCompraFocusGained
        jTextFieldPrecoCompra.selectAll();
    }//GEN-LAST:event_jTextFieldPrecoCompraFocusGained

    private void jTextFieldPrecoVendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPrecoVendaFocusGained
        jTextFieldPrecoVenda.selectAll();
    }//GEN-LAST:event_jTextFieldPrecoVendaFocusGained

    public void preencherCombo() {

        conecta.conexao();
        conecta.executaSQL("select * from fornecedor order by nome_fornecedor");
        try {
            conecta.rs.first();
            jComboBoxFornecedor.removeAllItems();
            do {

                jComboBoxFornecedor.addItem(conecta.rs.getString("nome_fornecedor"));

            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Selecionar os Dados" + ex);

        } finally {

            conecta.desconecta();

        }

        jComboBoxFornecedor.setSelectedItem("NAO CADASTRADO");

    }

    public void preencherComboCategorias() {

        conecta.conexao();
        conecta.executaSQL("select * from categorias order by nome_categoria");
        try {
            conecta.rs.first();
            jComboBoxCategorias.removeAllItems();
            do {

                jComboBoxCategorias.addItem(conecta.rs.getString("nome_categoria"));

            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Selecionar os Dados" + ex);

        } finally {

            conecta.desconecta();

        }

    }

    public void limpaCampos() {
        jTextFieldBarras.setText("");
        jTextFieldCodigo.setText("");
        jTextFieldPrecoCompra.setText("");
        jTextFieldLucroEsperado.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldProduto.setText("");
        jTextFieldQuantidadeMinima.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldLucro.setText("");

    }

    public void preencherTabela(String SQL) {

        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"Código", "Nome Produto", "Preco de Compra", "Preco de Venda", "Lucro Venda", "Margem Bruta %", "Estoque", "Fornecedor"};
        conecta.conexao();
        conecta.executaSQL(SQL);

        try {

            conecta.rs.first();

            do {
                float preCompra = conecta.rs.getFloat("preco_compra");
                float lucCompra = conecta.rs.getFloat("lucro_esperado");
                float lucVenda = conecta.rs.getFloat("lucrovenda");
                float preVenda = conecta.rs.getFloat("preco_venda");
                dados.add(new Object[]{conecta.rs.getInt("id_produto"), conecta.rs.getString("nome_produto"), df.format(preCompra), df.format(preVenda), df.format(lucVenda), df.format(lucCompra), conecta.rs.getInt("quantidade"), conecta.rs.getString("nome_fornecedor")});
            } while (conecta.rs.next());
        } catch (Exception e) {

            //JOptionPane.showMessageDialog(null, "ERRO AO CONECTAR"+ e);
        }

        ModeloTabela modelo = new ModeloTabela(dados, Colunas);

        tabela.setModel(modelo);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabela.getColumnModel().getColumn(0).setResizable(false);
        tabela.getColumnModel().getColumn(1).setPreferredWidth(300);
        tabela.getColumnModel().getColumn(1).setResizable(false);
        tabela.getColumnModel().getColumn(2).setPreferredWidth(150);
        tabela.getColumnModel().getColumn(2).setResizable(false);
        tabela.getColumnModel().getColumn(3).setPreferredWidth(150);
        tabela.getColumnModel().getColumn(3).setResizable(false);
        tabela.getColumnModel().getColumn(4).setPreferredWidth(150);
        tabela.getColumnModel().getColumn(4).setResizable(false);
        tabela.getColumnModel().getColumn(5).setPreferredWidth(150);
        tabela.getColumnModel().getColumn(5).setResizable(false);
        tabela.getColumnModel().getColumn(6).setPreferredWidth(100);
        tabela.getColumnModel().getColumn(6).setResizable(false);
        tabela.getColumnModel().getColumn(7).setPreferredWidth(230);
        tabela.getColumnModel().getColumn(7).setResizable(false);

        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setAutoResizeMode(tabela.AUTO_RESIZE_OFF);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tabela.setRowHeight(28);

    }

    public void IniciaId() {

        try {
            preencherTabela("select id_produto from produto");
            conecta.rs.last();
            idProd = conecta.rs.getInt("id_produto");
            jTextFieldCodigo.setText(String.valueOf(idProd + 1));
        } catch (SQLException ex) {
            Logger.getLogger(FrmCadastraProduto.class.getName()).log(Level.SEVERE, null, ex);
        } finally {

            conecta.desconecta();

        }

    }

    public void desabilitarCampos() {

        jTextFieldBarras.setEnabled(false);
        jTextFieldLucroEsperado.setEnabled(false);
        jTextFieldPrecoCompra.setEnabled(false);
        jTextFieldPrecoVenda.setEnabled(false);
        jTextFieldProduto.setEnabled(false);
        jTextFieldQuantidade.setEnabled(false);
        jTextFieldQuantidadeMinima.setEnabled(false);
        jButtonSalvar.setEnabled(false);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastraProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastraProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastraProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastraProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastraProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVisualizar;
    private javax.swing.JComboBox<String> jComboBoxCategorias;
    private javax.swing.JComboBox<String> jComboBoxFornecedor;
    private javax.swing.JComboBox<String> jComboBoxUnidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCarregando;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldBarras;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldLucro;
    private javax.swing.JTextField jTextFieldLucroEsperado;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldPrecoCompra;
    private javax.swing.JTextField jTextFieldPrecoVenda;
    private javax.swing.JTextField jTextFieldProduto;
    private javax.swing.JTextField jTextFieldQuantidade;
    private javax.swing.JTextField jTextFieldQuantidadeMinima;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

    private void novoProduto() {
        javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F6, 0), "novo");
        this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("novo", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            public void actionPerformed(ActionEvent arg0) {
                jButtonNovo.doClick();
            }
        });
    }

    private void salvaProduto() {
        javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0), "salvar");
        this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("salvar", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            public void actionPerformed(ActionEvent arg0) {
                jButtonSalvar.doClick();
            }
        });
    }

    private void EditaProduto() {
        javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F8, 0), "edita");
        this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("edita", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            public void actionPerformed(ActionEvent arg0) {
                jButtonEditar.doClick();
            }
        });
    }

    private void ExcluirProduto() {
        javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_DELETE, 0), "exclui");
        this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("exclui", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            public void actionPerformed(ActionEvent arg0) {
                jButtonExcluir.doClick();
            }
        });
    }

    private void Sair() {
        javax.swing.InputMap inputMap = this.getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escape");
        this.getRootPane().setInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("escape", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            public void actionPerformed(ActionEvent arg0) {
                jButtonSair.doClick();
            }
        });
    }

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
